version = "3.8.3"
runner.dialect = scala3
maxColumn = 100
indent.main = 2
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
danglingParentheses.preset = false
trailingCommas = never
align.preset = none
docstrings.style = Asterisk
